CREATE TABLE public."Payments" (
    id integer NOT NULL,
    order_id integer,
    paid_at timestamp without time zone,
    payment_method character varying(50),
    status character varying(50)
);

ALTER TABLE public."Payments" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Payments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.wishlist (
    id integer CONSTRAINT "Wishlist_id_not_null" NOT NULL,
    name character varying(250),
    user_id integer,
    product_id integer
);

ALTER TABLE public.wishlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Wishlist_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.category (
    id integer NOT NULL,
    name character varying(100)
);

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.orders (
    id integer NOT NULL,
    winkelwagen_users_id integer,
    total numeric(10,2),
    payment_status boolean,
    created_at timestamp without time zone
);

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.password_reset_tokens (
    id integer NOT NULL,
    user_id integer NOT NULL,
    token character varying(255) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    used boolean DEFAULT false
);

CREATE SEQUENCE public.password_reset_tokens_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.password_reset_tokens_id_seq OWNED BY public.password_reset_tokens.id;

CREATE TABLE public.product_categories (
    id integer NOT NULL,
    product_id integer,
    category_id integer
);

ALTER TABLE public.product_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.products (
    id integer NOT NULL,
    product_image character varying(250),
    name character varying(100),
    description character varying(250),
    price numeric(10,2),
    team_id integer
);

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.teams (
    id integer NOT NULL,
    name character varying(250),
    type character varying(250)
);

ALTER TABLE public.teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    id integer NOT NULL,
    first_name character varying(250),
    last_name character varying(250),
    username character varying(250),
    email character varying(250),
    password character varying(250),
    address character varying(250),
    postcode character varying(20),
    role character varying(20) DEFAULT 'user'::character varying NOT NULL
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.winkelwagen (
    winkelwagen_users_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer
);

CREATE TABLE public.winkelwagen_users (
    id integer NOT NULL,
    user_id integer,
    created_at timestamp without time zone
);

ALTER TABLE public.winkelwagen_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.winkelwagen_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- *** ADDED: order_items table ***
CREATE SEQUENCE public.order_items_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE public.order_items (
    id integer NOT NULL DEFAULT nextval('public.order_items_id_seq'),
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    price numeric(10,2) NOT NULL
);

ALTER SEQUENCE public.order_items_id_seq OWNED BY public.order_items.id;

-- *** ADDED: cart_details view ***
CREATE VIEW public.cart_details AS
    SELECT wu.user_id,
           w.winkelwagen_users_id,
           w.product_id,
           w.quantity,
           wu.created_at
    FROM public.winkelwagen w
    JOIN public.winkelwagen_users wu ON (w.winkelwagen_users_id = wu.id);


-- DEFAULTS
ALTER TABLE ONLY public.password_reset_tokens ALTER COLUMN id SET DEFAULT nextval('public.password_reset_tokens_id_seq'::regclass);


-- CONSTRAINTS
ALTER TABLE ONLY public."Payments"
    ADD CONSTRAINT "Payments_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT "Wishlist_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_name_key UNIQUE (name);

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_token_key UNIQUE (token);

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_name_key UNIQUE (name);

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.winkelwagen
    ADD CONSTRAINT winkelwagen_pkey PRIMARY KEY (winkelwagen_users_id, product_id);

ALTER TABLE ONLY public.winkelwagen_users
    ADD CONSTRAINT winkelwagen_users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.winkelwagen_users
    ADD CONSTRAINT winkelwagen_users_user_id_key UNIQUE (user_id);


-- INDEXES
CREATE UNIQUE INDEX product_categories_product_id_category_id_idx ON public.product_categories USING btree (product_id, category_id);


-- FOREIGN KEYS
ALTER TABLE ONLY public."Payments"
    ADD CONSTRAINT "Payments_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id) DEFERRABLE;

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT "Wishlist_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) DEFERRABLE;

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT "Wishlist_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE;

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_winkelwagen_users_id_fkey FOREIGN KEY (winkelwagen_users_id) REFERENCES public.winkelwagen_users(id) DEFERRABLE;

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.category(id) DEFERRABLE;

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) DEFERRABLE;

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id) DEFERRABLE;

ALTER TABLE ONLY public.winkelwagen
    ADD CONSTRAINT winkelwagen_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) DEFERRABLE;

ALTER TABLE ONLY public.winkelwagen_users
    ADD CONSTRAINT winkelwagen_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE;

ALTER TABLE ONLY public.winkelwagen
    ADD CONSTRAINT winkelwagen_winkelwagen_users_id_fkey FOREIGN KEY (winkelwagen_users_id) REFERENCES public.winkelwagen_users(id) DEFERRABLE;
