
CREATE TABLE public."Payments" (
    id integer NOT NULL,
    order_id integer,
    paid_at timestamp without time zone,
    payment_method character varying(50),
    status character varying(50)
);

--
-- TOC entry 234 (class 1259 OID 16588)
-- Name: Payments_id_seq; Type: SEQUENCE; Schema: public; Owner: db_admin
--

ALTER TABLE public."Payments" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Payments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16596)
-- Name: wishlist; Type: TABLE; Schema: public; Owner: db_admin
--

CREATE TABLE public.wishlist (
    id integer CONSTRAINT "Wishlist_id_not_null" NOT NULL,
    name character varying(250),
    user_id integer,
    product_id integer
);

--
-- TOC entry 236 (class 1259 OID 16595)
-- Name: Wishlist_id_seq; Type: SEQUENCE; Schema: public; Owner: db_admin
--

ALTER TABLE public.wishlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Wishlist_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16566)
-- Name: category; Type: TABLE; Schema: public; Owner: db_admin
--

CREATE TABLE public.category (
    id integer NOT NULL,
    name character varying(100)
);

--
-- TOC entry 228 (class 1259 OID 16565)
-- Name: category_id_seq; Type: SEQUENCE; Schema: public; Owner: db_admin
--

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16582)
-- Name: orders; Type: TABLE; Schema: public; Owner: db_admin
--

CREATE TABLE public.orders (
    id integer NOT NULL,
    winkelwagen_users_id integer,
    total numeric(10,2),
    payment_status boolean,
    created_at timestamp without time zone
);

--
-- TOC entry 232 (class 1259 OID 16581)
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: db_admin
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16681)
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: db_admin
--

CREATE TABLE public.password_reset_tokens (
    id integer NOT NULL,
    user_id integer NOT NULL,
    token character varying(255) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    used boolean DEFAULT false
);

--
-- TOC entry 238 (class 1259 OID 16680)
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: db_admin
--

CREATE SEQUENCE public.password_reset_tokens_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- TOC entry 3622 (class 0 OID 0)
-- Dependencies: 238
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: db_admin
--

ALTER SEQUENCE public.password_reset_tokens_id_seq OWNED BY public.password_reset_tokens.id;


--
-- TOC entry 231 (class 1259 OID 16575)
-- Name: product_categories; Type: TABLE; Schema: public; Owner: db_admin
--

CREATE TABLE public.product_categories (
    id integer NOT NULL,
    product_id integer,
    category_id integer
);

--
-- TOC entry 230 (class 1259 OID 16574)
-- Name: product_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: db_admin
--

ALTER TABLE public.product_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16530)
-- Name: products; Type: TABLE; Schema: public; Owner: db_admin
--

CREATE TABLE public.products (
    id integer NOT NULL,
    product_image character varying(250),
    name character varying(100),
    description character varying(250),
    price numeric(10,2),
    team_id integer
);

--
-- TOC entry 221 (class 1259 OID 16529)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: db_admin
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16539)
-- Name: teams; Type: TABLE; Schema: public; Owner: db_admin
--

CREATE TABLE public.teams (
    id integer NOT NULL,
    name character varying(250),
    type character varying(250)
);

--
-- TOC entry 223 (class 1259 OID 16538)
-- Name: teams_id_seq; Type: SEQUENCE; Schema: public; Owner: db_admin
--

ALTER TABLE public.teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16519)
-- Name: users; Type: TABLE; Schema: public; Owner: db_admin
--

CREATE TABLE public.users (
    id integer NOT NULL,
    first_name character varying(250),
    last_name character varying(250),
    username character varying(250),
    email character varying(250),
    password character varying(250),
    address character varying(250),
    postcode character varying(20),
    role character varying(20) DEFAULT 'user'::character varying NOT NULL
);

--
-- TOC entry 219 (class 1259 OID 16518)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: db_admin
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16558)
-- Name: winkelwagen; Type: TABLE; Schema: public; Owner: db_admin
--

CREATE TABLE public.winkelwagen (
    winkelwagen_users_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer
);

--
-- TOC entry 226 (class 1259 OID 16550)
-- Name: winkelwagen_users; Type: TABLE; Schema: public; Owner: db_admin
--

CREATE TABLE public.winkelwagen_users (
    id integer NOT NULL,
    user_id integer,
    created_at timestamp without time zone
);

--
-- TOC entry 225 (class 1259 OID 16549)
-- Name: winkelwagen_users_id_seq; Type: SEQUENCE; Schema: public; Owner: db_admin
--

ALTER TABLE public.winkelwagen_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.winkelwagen_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3423 (class 2604 OID 16684)
-- Name: password_reset_tokens id; Type: DEFAULT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.password_reset_tokens ALTER COLUMN id SET DEFAULT nextval('public.password_reset_tokens_id_seq'::regclass);


--
-- TOC entry 3451 (class 2606 OID 16594)
-- Name: Payments Payments_pkey; Type: CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public."Payments"
    ADD CONSTRAINT "Payments_pkey" PRIMARY KEY (id);


--
-- TOC entry 3453 (class 2606 OID 16601)
-- Name: wishlist Wishlist_pkey; Type: CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT "Wishlist_pkey" PRIMARY KEY (id);


--
-- TOC entry 3442 (class 2606 OID 16573)
-- Name: category category_name_key; Type: CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_name_key UNIQUE (name);


--
-- TOC entry 3444 (class 2606 OID 16571)
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);


--
-- TOC entry 3449 (class 2606 OID 16587)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- TOC entry 3455 (class 2606 OID 16691)
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- TOC entry 3457 (class 2606 OID 16693)
-- Name: password_reset_tokens password_reset_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_token_key UNIQUE (token);


--
-- TOC entry 3446 (class 2606 OID 16580)
-- Name: product_categories product_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_pkey PRIMARY KEY (id);


--
-- TOC entry 3430 (class 2606 OID 16537)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 3432 (class 2606 OID 16548)
-- Name: teams teams_name_key; Type: CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_name_key UNIQUE (name);


--
-- TOC entry 3434 (class 2606 OID 16546)
-- Name: teams teams_pkey; Type: CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);


--
-- TOC entry 3426 (class 2606 OID 16528)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 3428 (class 2606 OID 16526)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3440 (class 2606 OID 16564)
-- Name: winkelwagen winkelwagen_pkey; Type: CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.winkelwagen
    ADD CONSTRAINT winkelwagen_pkey PRIMARY KEY (winkelwagen_users_id, product_id);


--
-- TOC entry 3436 (class 2606 OID 16555)
-- Name: winkelwagen_users winkelwagen_users_pkey; Type: CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.winkelwagen_users
    ADD CONSTRAINT winkelwagen_users_pkey PRIMARY KEY (id);


--
-- TOC entry 3438 (class 2606 OID 16557)
-- Name: winkelwagen_users winkelwagen_users_user_id_key; Type: CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.winkelwagen_users
    ADD CONSTRAINT winkelwagen_users_user_id_key UNIQUE (user_id);


--
-- TOC entry 3447 (class 1259 OID 16602)
-- Name: product_categories_product_id_category_id_idx; Type: INDEX; Schema: public; Owner: db_admin
--

CREATE UNIQUE INDEX product_categories_product_id_category_id_idx ON public.product_categories USING btree (product_id, category_id);


--
-- TOC entry 3465 (class 2606 OID 16633)
-- Name: Payments Payments_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public."Payments"
    ADD CONSTRAINT "Payments_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id) DEFERRABLE;


--
-- TOC entry 3466 (class 2606 OID 16643)
-- Name: wishlist Wishlist_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT "Wishlist_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) DEFERRABLE;


--
-- TOC entry 3467 (class 2606 OID 16638)
-- Name: wishlist Wishlist_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT "Wishlist_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE;


--
-- TOC entry 3464 (class 2606 OID 16628)
-- Name: orders orders_winkelwagen_users_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_winkelwagen_users_id_fkey FOREIGN KEY (winkelwagen_users_id) REFERENCES public.winkelwagen_users(id) DEFERRABLE;


--
-- TOC entry 3468 (class 2606 OID 16694)
-- Name: password_reset_tokens password_reset_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 3462 (class 2606 OID 16623)
-- Name: product_categories product_categories_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.category(id) DEFERRABLE;


--
-- TOC entry 3463 (class 2606 OID 16618)
-- Name: product_categories product_categories_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) DEFERRABLE;


--
-- TOC entry 3458 (class 2606 OID 16648)
-- Name: products products_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id) DEFERRABLE;


--
-- TOC entry 3460 (class 2606 OID 16613)
-- Name: winkelwagen winkelwagen_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.winkelwagen
    ADD CONSTRAINT winkelwagen_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) DEFERRABLE;


--
-- TOC entry 3459 (class 2606 OID 16603)
-- Name: winkelwagen_users winkelwagen_users_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.winkelwagen_users
    ADD CONSTRAINT winkelwagen_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE;


--
-- TOC entry 3461 (class 2606 OID 16608)
-- Name: winkelwagen winkelwagen_winkelwagen_users_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: db_admin
--

ALTER TABLE ONLY public.winkelwagen
    ADD CONSTRAINT winkelwagen_winkelwagen_users_id_fkey FOREIGN KEY (winkelwagen_users_id) REFERENCES public.winkelwagen_users(id) DEFERRABLE;
