@WebshopApi_HostAddress = http://localhost:5261

GET {{WebshopApi_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{WebshopApi_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "email": "john.doe@gmail.com",
  "password": "John"
}