name: CI Pipeline

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Cache NuGet Packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ hashFiles('**/*.csproj')}}
          restore-keys: |
            nuget-${{ runner.os }}
      
      - name: check for vulnerable packages
        run: dotnet list Backend/WebshopApi/WebshopApi.csproj package --vulnerable

      - name: Restore Dependencies
        run: dotnet restore Backend/WebshopApi/WebshopApi.csproj
      
      - name: Build
        working-directory: Backend/WebshopApi
        run: dotnet build WebshopApi.csproj --no-restore
      